version: '3'

services:
  server:
    build: ./build/server
    ports:
      - "8000:8000"
    volumes:
      - ${CONTENT_FOLDER_PATH}:/content
    network_mode: "host"
  daemon:
    build: ./build/daemon
    volumes:
      - ${CONTENT_FOLDER_PATH}:/content
    network_mode: "host"
